import { db } from '@/db';
import { employees } from '@/db/schema';

async function main() {
    const sampleEmployees = [
        {
            employee_code: 'ENG-001',
            first_name: 'Sarah',
            last_name: 'Chen',
            email: 'sarah.chen@company.com',
            phone: '(555) 123-4501',
            date_of_birth: '1985-03-15',
            gender: 'Female',
            marital_status: 'Married',
            address: '123 Tech Boulevard',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94102',
            country: 'United States',
            department: 'Engineering',
            designation: 'VP Engineering',
            role: 'VP Engineering',
            manager_id: null,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2018-06-15',
            date_of_leaving: null,
            salary: 185000.00,
            bank_account_number: '1234567890',
            bank_name: 'Chase',
            emergency_contact_name: 'Michael Chen',
            emergency_contact_phone: '(555) 123-4502',
            avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
            created_at: new Date('2018-06-15').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'SAL-001',
            first_name: 'James',
            last_name: 'Rodriguez',
            email: 'james.rodriguez@company.com',
            phone: '(555) 123-4503',
            date_of_birth: '1983-07-22',
            gender: 'Male',
            marital_status: 'Single',
            address: '456 Market Street',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94103',
            country: 'United States',
            department: 'Sales',
            designation: 'VP Sales',
            role: 'VP Sales',
            manager_id: null,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2019-01-10',
            date_of_leaving: null,
            salary: 175000.00,
            bank_account_number: '2345678901',
            bank_name: 'Bank of America',
            emergency_contact_name: 'Maria Rodriguez',
            emergency_contact_phone: '(555) 123-4504',
            avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
            created_at: new Date('2019-01-10').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'FIN-001',
            first_name: 'Emily',
            last_name: 'Thompson',
            email: 'emily.thompson@company.com',
            phone: '(555) 123-4505',
            date_of_birth: '1987-11-08',
            gender: 'Female',
            marital_status: 'Married',
            address: '789 Financial Plaza',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94104',
            country: 'United States',
            department: 'Finance',
            designation: 'CFO',
            role: 'CFO',
            manager_id: null,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2017-09-01',
            date_of_leaving: null,
            salary: 195000.00,
            bank_account_number: '3456789012',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'David Thompson',
            emergency_contact_phone: '(555) 123-4506',
            avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
            created_at: new Date('2017-09-01').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'MKT-001',
            first_name: 'Alex',
            last_name: 'Kim',
            email: 'alex.kim@company.com',
            phone: '(555) 123-4507',
            date_of_birth: '1986-05-14',
            gender: 'Male',
            marital_status: 'Single',
            address: '321 Creative Drive',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94105',
            country: 'United States',
            department: 'Marketing',
            designation: 'VP Marketing',
            role: 'VP Marketing',
            manager_id: null,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2019-03-20',
            date_of_leaving: null,
            salary: 165000.00,
            bank_account_number: '4567890123',
            bank_name: 'Citibank',
            emergency_contact_name: 'Jennifer Kim',
            emergency_contact_phone: '(555) 123-4508',
            avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
            created_at: new Date('2019-03-20').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-002',
            first_name: 'Michael',
            last_name: 'Anderson',
            email: 'michael.anderson@company.com',
            phone: '(555) 123-4509',
            date_of_birth: '1988-09-25',
            gender: 'Male',
            marital_status: 'Married',
            address: '555 Innovation Way',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94106',
            country: 'United States',
            department: 'Engineering',
            designation: 'Engineering Director',
            role: 'Engineering Director',
            manager_id: 1,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2019-07-15',
            date_of_leaving: null,
            salary: 155000.00,
            bank_account_number: '5678901234',
            bank_name: 'Chase',
            emergency_contact_name: 'Lisa Anderson',
            emergency_contact_phone: '(555) 123-4510',
            avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
            created_at: new Date('2019-07-15').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-003',
            first_name: 'Priya',
            last_name: 'Patel',
            email: 'priya.patel@company.com',
            phone: '(555) 123-4511',
            date_of_birth: '1990-02-18',
            gender: 'Female',
            marital_status: 'Single',
            address: '888 Developer Lane',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94107',
            country: 'United States',
            department: 'Engineering',
            designation: 'Senior Engineering Manager',
            role: 'Engineering Manager',
            manager_id: 5,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2020-01-20',
            date_of_leaving: null,
            salary: 145000.00,
            bank_account_number: '6789012345',
            bank_name: 'Bank of America',
            emergency_contact_name: 'Rajesh Patel',
            emergency_contact_phone: '(555) 123-4512',
            avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
            created_at: new Date('2020-01-20').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-004',
            first_name: 'David',
            last_name: 'Martinez',
            email: 'david.martinez@company.com',
            phone: '(555) 123-4513',
            date_of_birth: '1991-06-30',
            gender: 'Male',
            marital_status: 'Married',
            address: '222 Software Street',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94108',
            country: 'United States',
            department: 'Engineering',
            designation: 'Senior Software Engineer',
            role: 'Software Engineer',
            manager_id: 6,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2020-08-10',
            date_of_leaving: null,
            salary: 135000.00,
            bank_account_number: '7890123456',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'Carmen Martinez',
            emergency_contact_phone: '(555) 123-4514',
            avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
            created_at: new Date('2020-08-10').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-005',
            first_name: 'Jessica',
            last_name: 'Lee',
            email: 'jessica.lee@company.com',
            phone: '(555) 123-4515',
            date_of_birth: '1992-12-05',
            gender: 'Female',
            marital_status: 'Single',
            address: '444 Code Avenue',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94109',
            country: 'United States',
            department: 'Engineering',
            designation: 'Software Engineer',
            role: 'Software Engineer',
            manager_id: 6,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-02-15',
            date_of_leaving: null,
            salary: 125000.00,
            bank_account_number: '8901234567',
            bank_name: 'Citibank',
            emergency_contact_name: 'Robert Lee',
            emergency_contact_phone: '(555) 123-4516',
            avatar_url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop',
            created_at: new Date('2021-02-15').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-006',
            first_name: 'Ryan',
            last_name: 'O\'Connor',
            email: 'ryan.oconnor@company.com',
            phone: '(555) 123-4517',
            date_of_birth: '1993-04-12',
            gender: 'Male',
            marital_status: 'Single',
            address: '666 Tech Park',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94110',
            country: 'United States',
            department: 'Engineering',
            designation: 'Software Engineer',
            role: 'Software Engineer',
            manager_id: 6,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-06-01',
            date_of_leaving: null,
            salary: 120000.00,
            bank_account_number: '9012345678',
            bank_name: 'Chase',
            emergency_contact_name: 'Patrick O\'Connor',
            emergency_contact_phone: '(555) 123-4518',
            avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop',
            created_at: new Date('2021-06-01').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-007',
            first_name: 'Amanda',
            last_name: 'Wilson',
            email: 'amanda.wilson@company.com',
            phone: '(555) 123-4519',
            date_of_birth: '1994-08-20',
            gender: 'Female',
            marital_status: 'Married',
            address: '777 Developer Court',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94111',
            country: 'United States',
            department: 'Engineering',
            designation: 'Junior Software Engineer',
            role: 'Software Engineer',
            manager_id: 6,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2022-01-10',
            date_of_leaving: null,
            salary: 110000.00,
            bank_account_number: '0123456789',
            bank_name: 'Bank of America',
            emergency_contact_name: 'Thomas Wilson',
            emergency_contact_phone: '(555) 123-4520',
            avatar_url: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400&fit=crop',
            created_at: new Date('2022-01-10').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-008',
            first_name: 'Kevin',
            last_name: 'Brown',
            email: 'kevin.brown@company.com',
            phone: '(555) 123-4521',
            date_of_birth: '1989-10-15',
            gender: 'Male',
            marital_status: 'Married',
            address: '999 Backend Boulevard',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94112',
            country: 'United States',
            department: 'Engineering',
            designation: 'Senior Software Engineer',
            role: 'Software Engineer',
            manager_id: 6,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2020-05-18',
            date_of_leaving: null,
            salary: 140000.00,
            bank_account_number: '1357924680',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'Sarah Brown',
            emergency_contact_phone: '(555) 123-4522',
            avatar_url: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop',
            created_at: new Date('2020-05-18').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-009',
            first_name: 'Maria',
            last_name: 'Garcia',
            email: 'maria.garcia@company.com',
            phone: '(555) 123-4523',
            date_of_birth: '1991-03-28',
            gender: 'Female',
            marital_status: 'Single',
            address: '111 Frontend Lane',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94113',
            country: 'United States',
            department: 'Engineering',
            designation: 'Software Engineer',
            role: 'Software Engineer',
            manager_id: 6,
            employment_type: 'Contract',
            employment_status: 'Active',
            date_of_joining: '2021-09-01',
            date_of_leaving: null,
            salary: 115000.00,
            bank_account_number: '2468013579',
            bank_name: 'Citibank',
            emergency_contact_name: 'Jose Garcia',
            emergency_contact_phone: '(555) 123-4524',
            avatar_url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=400&fit=crop',
            created_at: new Date('2021-09-01').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-010',
            first_name: 'Daniel',
            last_name: 'Taylor',
            email: 'daniel.taylor@company.com',
            phone: '(555) 123-4525',
            date_of_birth: '1995-01-22',
            gender: 'Male',
            marital_status: 'Single',
            address: '333 Fullstack Street',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94114',
            country: 'United States',
            department: 'Engineering',
            designation: 'Junior Software Engineer',
            role: 'Software Engineer',
            manager_id: 6,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2022-07-15',
            date_of_leaving: null,
            salary: 105000.00,
            bank_account_number: '3691258024',
            bank_name: 'Chase',
            emergency_contact_name: 'Jennifer Taylor',
            emergency_contact_phone: '(555) 123-4526',
            avatar_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=400&fit=crop',
            created_at: new Date('2022-07-15').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-011',
            first_name: 'Sophie',
            last_name: 'Zhang',
            email: 'sophie.zhang@company.com',
            phone: '(555) 123-4527',
            date_of_birth: '1993-07-08',
            gender: 'Female',
            marital_status: 'Married',
            address: '555 DevOps Drive',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94115',
            country: 'United States',
            department: 'Engineering',
            designation: 'DevOps Engineer',
            role: 'DevOps Engineer',
            manager_id: 6,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-03-10',
            date_of_leaving: null,
            salary: 130000.00,
            bank_account_number: '4825169370',
            bank_name: 'Bank of America',
            emergency_contact_name: 'Wei Zhang',
            emergency_contact_phone: '(555) 123-4528',
            avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
            created_at: new Date('2021-03-10').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-012',
            first_name: 'Brandon',
            last_name: 'Mitchell',
            email: 'brandon.mitchell@company.com',
            phone: '(555) 123-4529',
            date_of_birth: '1990-11-30',
            gender: 'Male',
            marital_status: 'Single',
            address: '777 Cloud Avenue',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94116',
            country: 'United States',
            department: 'Engineering',
            designation: 'Senior DevOps Engineer',
            role: 'DevOps Engineer',
            manager_id: 6,
            employment_type: 'Part-time',
            employment_status: 'Active',
            date_of_joining: '2020-10-05',
            date_of_leaving: null,
            salary: 95000.00,
            bank_account_number: '5936047281',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'Rachel Mitchell',
            emergency_contact_phone: '(555) 123-4530',
            avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
            created_at: new Date('2020-10-05').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'ENG-013',
            first_name: 'Nicole',
            last_name: 'Johnson',
            email: 'nicole.johnson@company.com',
            phone: '(555) 123-4531',
            date_of_birth: '1992-05-17',
            gender: 'Female',
            marital_status: 'Married',
            address: '999 QA Boulevard',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94117',
            country: 'United States',
            department: 'Engineering',
            designation: 'QA Engineer',
            role: 'QA Engineer',
            manager_id: 6,
            employment_type: 'Full-time',
            employment_status: 'Inactive',
            date_of_joining: '2021-11-20',
            date_of_leaving: null,
            salary: 118000.00,
            bank_account_number: '6047283915',
            bank_name: 'Citibank',
            emergency_contact_name: 'Mark Johnson',
            emergency_contact_phone: '(555) 123-4532',
            avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
            created_at: new Date('2021-11-20').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'SAL-002',
            first_name: 'Robert',
            last_name: 'Davis',
            email: 'robert.davis@company.com',
            phone: '(555) 123-4533',
            date_of_birth: '1987-09-14',
            gender: 'Male',
            marital_status: 'Married',
            address: '222 Sales Plaza',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94118',
            country: 'United States',
            department: 'Sales',
            designation: 'Sales Director',
            role: 'Sales Director',
            manager_id: 2,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2019-08-01',
            date_of_leaving: null,
            salary: 150000.00,
            bank_account_number: '7158924603',
            bank_name: 'Chase',
            emergency_contact_name: 'Jennifer Davis',
            emergency_contact_phone: '(555) 123-4534',
            avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
            created_at: new Date('2019-08-01').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'SAL-003',
            first_name: 'Linda',
            last_name: 'Martinez',
            email: 'linda.martinez@company.com',
            phone: '(555) 123-4535',
            date_of_birth: '1989-12-03',
            gender: 'Female',
            marital_status: 'Single',
            address: '444 Revenue Street',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94119',
            country: 'United States',
            department: 'Sales',
            designation: 'Sales Manager',
            role: 'Sales Manager',
            manager_id: 17,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2020-02-15',
            date_of_leaving: null,
            salary: 135000.00,
            bank_account_number: '8269135704',
            bank_name: 'Bank of America',
            emergency_contact_name: 'Carlos Martinez',
            emergency_contact_phone: '(555) 123-4536',
            avatar_url: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=400&h=400&fit=crop',
            created_at: new Date('2020-02-15').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'SAL-004',
            first_name: 'Christopher',
            last_name: 'White',
            email: 'christopher.white@company.com',
            phone: '(555) 123-4537',
            date_of_birth: '1991-04-25',
            gender: 'Male',
            marital_status: 'Married',
            address: '666 Deal Avenue',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94120',
            country: 'United States',
            department: 'Sales',
            designation: 'Senior Sales Representative',
            role: 'Sales Representative',
            manager_id: 18,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2020-09-10',
            date_of_leaving: null,
            salary: 115000.00,
            bank_account_number: '9370246815',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'Michelle White',
            emergency_contact_phone: '(555) 123-4538',
            avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
            created_at: new Date('2020-09-10').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'SAL-005',
            first_name: 'Ashley',
            last_name: 'Harris',
            email: 'ashley.harris@company.com',
            phone: '(555) 123-4539',
            date_of_birth: '1993-08-19',
            gender: 'Female',
            marital_status: 'Single',
            address: '888 Client Road',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94121',
            country: 'United States',
            department: 'Sales',
            designation: 'Sales Representative',
            role: 'Sales Representative',
            manager_id: 18,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-05-20',
            date_of_leaving: null,
            salary: 105000.00,
            bank_account_number: '0481357926',
            bank_name: 'Citibank',
            emergency_contact_name: 'Brian Harris',
            emergency_contact_phone: '(555) 123-4540',
            avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
            created_at: new Date('2021-05-20').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'SAL-006',
            first_name: 'Matthew',
            last_name: 'Clark',
            email: 'matthew.clark@company.com',
            phone: '(555) 123-4541',
            date_of_birth: '1992-02-28',
            gender: 'Male',
            marital_status: 'Married',
            address: '123 Pipeline Drive',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94122',
            country: 'United States',
            department: 'Sales',
            designation: 'Sales Representative',
            role: 'Sales Representative',
            manager_id: 18,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-08-15',
            date_of_leaving: null,
            salary: 102000.00,
            bank_account_number: '1592468037',
            bank_name: 'Chase',
            emergency_contact_name: 'Laura Clark',
            emergency_contact_phone: '(555) 123-4542',
            avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop',
            created_at: new Date('2021-08-15').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'SAL-007',
            first_name: 'Elizabeth',
            last_name: 'Lewis',
            email: 'elizabeth.lewis@company.com',
            phone: '(555) 123-4543',
            date_of_birth: '1994-06-10',
            gender: 'Female',
            marital_status: 'Single',
            address: '456 Quota Street',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94123',
            country: 'United States',
            department: 'Sales',
            designation: 'Junior Sales Representative',
            role: 'Sales Representative',
            manager_id: 18,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2022-03-01',
            date_of_leaving: null,
            salary: 95000.00,
            bank_account_number: '2603579148',
            bank_name: 'Bank of America',
            emergency_contact_name: 'Richard Lewis',
            emergency_contact_phone: '(555) 123-4544',
            avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
            created_at: new Date('2022-03-01').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'SAL-008',
            first_name: 'Anthony',
            last_name: 'Walker',
            email: 'anthony.walker@company.com',
            phone: '(555) 123-4545',
            date_of_birth: '1990-10-07',
            gender: 'Male',
            marital_status: 'Married',
            address: '789 Commission Lane',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94124',
            country: 'United States',
            department: 'Sales',
            designation: 'Senior Sales Representative',
            role: 'Sales Representative',
            manager_id: 18,
            employment_type: 'Contract',
            employment_status: 'Active',
            date_of_joining: '2020-12-01',
            date_of_leaving: null,
            salary: 108000.00,
            bank_account_number: '3714826059',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'Stephanie Walker',
            emergency_contact_phone: '(555) 123-4546',
            avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
            created_at: new Date('2020-12-01').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'SAL-009',
            first_name: 'Samantha',
            last_name: 'Hall',
            email: 'samantha.hall@company.com',
            phone: '(555) 123-4547',
            date_of_birth: '1995-01-13',
            gender: 'Female',
            marital_status: 'Single',
            address: '321 Target Boulevard',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94125',
            country: 'United States',
            department: 'Sales',
            designation: 'Sales Development Representative',
            role: 'Sales Representative',
            manager_id: 18,
            employment_type: 'Full-time',
            employment_status: 'Terminated',
            date_of_joining: '2022-09-15',
            date_of_leaving: '2023-12-31',
            salary: 85000.00,
            bank_account_number: '4825937160',
            bank_name: 'Citibank',
            emergency_contact_name: 'Thomas Hall',
            emergency_contact_phone: '(555) 123-4548',
            avatar_url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop',
            created_at: new Date('2022-09-15').toISOString(),
            updated_at: new Date('2023-12-31').toISOString(),
        },
        {
            employee_code: 'SAL-010',
            first_name: 'Joshua',
            last_name: 'Young',
            email: 'joshua.young@company.com',
            phone: '(555) 123-4549',
            date_of_birth: '1993-11-29',
            gender: 'Male',
            marital_status: 'Married',
            address: '654 Prospect Avenue',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94126',
            country: 'United States',
            department: 'Sales',
            designation: 'Sales Representative',
            role: 'Sales Representative',
            manager_id: 18,
            employment_type: 'Part-time',
            employment_status: 'Active',
            date_of_joining: '2021-11-10',
            date_of_leaving: null,
            salary: 72000.00,
            bank_account_number: '5936048271',
            bank_name: 'Chase',
            emergency_contact_name: 'Amanda Young',
            emergency_contact_phone: '(555) 123-4550',
            avatar_url: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop',
            created_at: new Date('2021-11-10').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'MKT-002',
            first_name: 'Rachel',
            last_name: 'Adams',
            email: 'rachel.adams@company.com',
            phone: '(555) 123-4551',
            date_of_birth: '1988-07-16',
            gender: 'Female',
            marital_status: 'Single',
            address: '987 Brand Street',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94127',
            country: 'United States',
            department: 'Marketing',
            designation: 'Marketing Director',
            role: 'Marketing Director',
            manager_id: 4,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2019-10-15',
            date_of_leaving: null,
            salary: 145000.00,
            bank_account_number: '6047159382',
            bank_name: 'Bank of America',
            emergency_contact_name: 'Steven Adams',
            emergency_contact_phone: '(555) 123-4552',
            avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
            created_at: new Date('2019-10-15').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'MKT-003',
            first_name: 'Thomas',
            last_name: 'Nelson',
            email: 'thomas.nelson@company.com',
            phone: '(555) 123-4553',
            date_of_birth: '1990-03-22',
            gender: 'Male',
            marital_status: 'Married',
            address: '234 Content Avenue',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94128',
            country: 'United States',
            department: 'Marketing',
            designation: 'Content Marketing Manager',
            role: 'Marketing Manager',
            manager_id: 27,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2020-06-01',
            date_of_leaving: null,
            salary: 125000.00,
            bank_account_number: '7158260493',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'Jessica Nelson',
            emergency_contact_phone: '(555) 123-4554',
            avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
            created_at: new Date('2020-06-01').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'MKT-004',
            first_name: 'Michelle',
            last_name: 'Carter',
            email: 'michelle.carter@company.com',
            phone: '(555) 123-4555',
            date_of_birth: '1992-09-18',
            gender: 'Female',
            marital_status: 'Single',
            address: '567 Social Media Lane',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94129',
            country: 'United States',
            department: 'Marketing',
            designation: 'Social Media Manager',
            role: 'Marketing Manager',
            manager_id: 27,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-01-15',
            date_of_leaving: null,
            salary: 115000.00,
            bank_account_number: '8269371504',
            bank_name: 'Citibank',
            emergency_contact_name: 'Daniel Carter',
            emergency_contact_phone: '(555) 123-4556',
            avatar_url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=400&fit=crop',
            created_at: new Date('2021-01-15').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'MKT-005',
            first_name: 'Brian',
            last_name: 'Mitchell',
            email: 'brian.mitchell@company.com',
            phone: '(555) 123-4557',
            date_of_birth: '1991-12-05',
            gender: 'Male',
            marital_status: 'Married',
            address: '890 SEO Boulevard',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94130',
            country: 'United States',
            department: 'Marketing',
            designation: 'SEO Specialist',
            role: 'Marketing Specialist',
            manager_id: 27,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-07-20',
            date_of_leaving: null,
            salary: 105000.00,
            bank_account_number: '9370482615',
            bank_name: 'Chase',
            emergency_contact_name: 'Emily Mitchell',
            emergency_contact_phone: '(555) 123-4558',
            avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
            created_at: new Date('2021-07-20').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'MKT-006',
            first_name: 'Angela',
            last_name: 'Roberts',
            email: 'angela.roberts@company.com',
            phone: '(555) 123-4559',
            date_of_birth: '1994-04-11',
            gender: 'Female',
            marital_status: 'Single',
            address: '123 Campaign Street',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94131',
            country: 'United States',
            department: 'Marketing',
            designation: 'Marketing Coordinator',
            role: 'Marketing Coordinator',
            manager_id: 27,
            employment_type: 'Contract',
            employment_status: 'Active',
            date_of_joining: '2022-02-10',
            date_of_leaving: null,
            salary: 85000.00,
            bank_account_number: '0481593726',
            bank_name: 'Bank of America',
            emergency_contact_name: 'William Roberts',
            emergency_contact_phone: '(555) 123-4560',
            avatar_url: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400&fit=crop',
            created_at: new Date('2022-02-10').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'MKT-007',
            first_name: 'Gregory',
            last_name: 'Turner',
            email: 'gregory.turner@company.com',
            phone: '(555) 123-4561',
            date_of_birth: '1993-08-27',
            gender: 'Male',
            marital_status: 'Married',
            address: '456 Analytics Avenue',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94132',
            country: 'United States',
            department: 'Marketing',
            designation: 'Marketing Analyst',
            role: 'Marketing Analyst',
            manager_id: 27,
            employment_type: 'Full-time',
            employment_status: 'Inactive',
            date_of_joining: '2021-10-05',
            date_of_leaving: null,
            salary: 98000.00,
            bank_account_number: '1592604837',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'Susan Turner',
            emergency_contact_phone: '(555) 123-4562',
            avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop',
            created_at: new Date('2021-10-05').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'MKT-008',
            first_name: 'Melissa',
            last_name: 'Phillips',
            email: 'melissa.phillips@company.com',
            phone: '(555) 123-4563',
            date_of_birth: '1995-02-14',
            gender: 'Female',
            marital_status: 'Single',
            address: '789 Design Drive',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94133',
            country: 'United States',
            department: 'Marketing',
            designation: 'Graphic Designer',
            role: 'Graphic Designer',
            manager_id: 27,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2022-05-18',
            date_of_leaving: null,
            salary: 92000.00,
            bank_account_number: '2603715948',
            bank_name: 'Citibank',
            emergency_contact_name: 'Robert Phillips',
            emergency_contact_phone: '(555) 123-4564',
            avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
            created_at: new Date('2022-05-18').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'HR-001',
            first_name: 'Patricia',
            last_name: 'Campbell',
            email: 'patricia.campbell@company.com',
            phone: '(555) 123-4565',
            date_of_birth: '1986-05-30',
            gender: 'Female',
            marital_status: 'Married',
            address: '321 People Street',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94134',
            country: 'United States',
            department: 'HR',
            designation: 'HR Director',
            role: 'HR Director',
            manager_id: null,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2018-03-10',
            date_of_leaving: null,
            salary: 155000.00,
            bank_account_number: '3714826059',
            bank_name: 'Chase',
            emergency_contact_name: 'George Campbell',
            emergency_contact_phone: '(555) 123-4566',
            avatar_url: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=400&h=400&fit=crop',
            created_at: new Date('2018-03-10').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'HR-002',
            first_name: 'Steven',
            last_name: 'Parker',
            email: 'steven.parker@company.com',
            phone: '(555) 123-4567',
            date_of_birth: '1989-11-12',
            gender: 'Male',
            marital_status: 'Single',
            address: '654 Talent Avenue',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94135',
            country: 'United States',
            department: 'HR',
            designation: 'HR Manager',
            role: 'HR Manager',
            manager_id: 35,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2020-04-15',
            date_of_leaving: null,
            salary: 125000.00,
            bank_account_number: '4825937160',
            bank_name: 'Bank of America',
            emergency_contact_name: 'Karen Parker',
            emergency_contact_phone: '(555) 123-4568',
            avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
            created_at: new Date('2020-04-15').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'HR-003',
            first_name: 'Deborah',
            last_name: 'Evans',
            email: 'deborah.evans@company.com',
            phone: '(555) 123-4569',
            date_of_birth: '1991-08-04',
            gender: 'Female',
            marital_status: 'Married',
            address: '987 Recruitment Road',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94136',
            country: 'United States',
            department: 'HR',
            designation: 'Recruiter',
            role: 'Recruiter',
            manager_id: 36,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-02-20',
            date_of_leaving: null,
            salary: 105000.00,
            bank_account_number: '5936048271',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'Paul Evans',
            emergency_contact_phone: '(555) 123-4570',
            avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
            created_at: new Date('2021-02-20').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'HR-004',
            first_name: 'Edward',
            last_name: 'Collins',
            email: 'edward.collins@company.com',
            phone: '(555) 123-4571',
            date_of_birth: '1993-01-17',
            gender: 'Male',
            marital_status: 'Single',
            address: '234 Benefits Boulevard',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94137',
            country: 'United States',
            department: 'HR',
            designation: 'HR Specialist',
            role: 'HR Specialist',
            manager_id: 36,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-09-10',
            date_of_leaving: null,
            salary: 95000.00,
            bank_account_number: '6047159382',
            bank_name: 'Citibank',
            emergency_contact_name: 'Nancy Collins',
            emergency_contact_phone: '(555) 123-4572',
            avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
            created_at: new Date('2021-09-10').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'HR-005',
            first_name: 'Sandra',
            last_name: 'Stewart',
            email: 'sandra.stewart@company.com',
            phone: '(555) 123-4573',
            date_of_birth: '1994-06-23',
            gender: 'Female',
            marital_status: 'Married',
            address: '567 Payroll Lane',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94138',
            country: 'United States',
            department: 'HR',
            designation: 'HR Coordinator',
            role: 'HR Coordinator',
            manager_id: 36,
            employment_type: 'Part-time',
            employment_status: 'Active',
            date_of_joining: '2022-04-01',
            date_of_leaving: null,
            salary: 68000.00,
            bank_account_number: '7158260493',
            bank_name: 'Chase',
            emergency_contact_name: 'Kenneth Stewart',
            emergency_contact_phone: '(555) 123-4574',
            avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
            created_at: new Date('2022-04-01').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'HR-006',
            first_name: 'Raymond',
            last_name: 'Morris',
            email: 'raymond.morris@company.com',
            phone: '(555) 123-4575',
            date_of_birth: '1992-10-09',
            gender: 'Male',
            marital_status: 'Single',
            address: '890 Training Avenue',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94139',
            country: 'United States',
            department: 'HR',
            designation: 'Training Specialist',
            role: 'Training Specialist',
            manager_id: 36,
            employment_type: 'Contract',
            employment_status: 'Terminated',
            date_of_joining: '2021-11-15',
            date_of_leaving: '2023-11-30',
            salary: 88000.00,
            bank_account_number: '8269371504',
            bank_name: 'Bank of America',
            emergency_contact_name: 'Betty Morris',
            emergency_contact_phone: '(555) 123-4576',
            avatar_url: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop',
            created_at: new Date('2021-11-15').toISOString(),
            updated_at: new Date('2023-11-30').toISOString(),
        },
        {
            employee_code: 'FIN-002',
            first_name: 'Kenneth',
            last_name: 'Rogers',
            email: 'kenneth.rogers@company.com',
            phone: '(555) 123-4577',
            date_of_birth: '1988-03-21',
            gender: 'Male',
            marital_status: 'Married',
            address: '123 Accounting Street',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94140',
            country: 'United States',
            department: 'Finance',
            designation: 'Finance Director',
            role: 'Finance Director',
            manager_id: 3,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2018-11-01',
            date_of_leaving: null,
            salary: 160000.00,
            bank_account_number: '9370482615',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'Dorothy Rogers',
            emergency_contact_phone: '(555) 123-4578',
            avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
            created_at: new Date('2018-11-01').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'FIN-003',
            first_name: 'Betty',
            last_name: 'Reed',
            email: 'betty.reed@company.com',
            phone: '(555) 123-4579',
            date_of_birth: '1990-07-14',
            gender: 'Female',
            marital_status: 'Single',
            address: '456 Budget Avenue',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94141',
            country: 'United States',
            department: 'Finance',
            designation: 'Senior Accountant',
            role: 'Accountant',
            manager_id: 42,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2020-03-15',
            date_of_leaving: null,
            salary: 115000.00,
            bank_account_number: '0481593726',
            bank_name: 'Citibank',
            emergency_contact_name: 'Harold Reed',
            emergency_contact_phone: '(555) 123-4580',
            avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
            created_at: new Date('2020-03-15').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'FIN-004',
            first_name: 'Gary',
            last_name: 'Cook',
            email: 'gary.cook@company.com',
            phone: '(555) 123-4581',
            date_of_birth: '1991-12-28',
            gender: 'Male',
            marital_status: 'Married',
            address: '789 Ledger Lane',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94142',
            country: 'United States',
            department: 'Finance',
            designation: 'Accountant',
            role: 'Accountant',
            manager_id: 42,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-05-10',
            date_of_leaving: null,
            salary: 105000.00,
            bank_account_number: '1592604837',
            bank_name: 'Chase',
            emergency_contact_name: 'Helen Cook',
            emergency_contact_phone: '(555) 123-4582',
            avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
            created_at: new Date('2021-05-10').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'FIN-005',
            first_name: 'Helen',
            last_name: 'Morgan',
            email: 'helen.morgan@company.com',
            phone: '(555) 123-4583',
            date_of_birth: '1993-04-06',
            gender: 'Female',
            marital_status: 'Single',
            address: '321 Treasury Road',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94143',
            country: 'United States',
            department: 'Finance',
            designation: 'Financial Analyst',
            role: 'Financial Analyst',
            manager_id: 42,
            employment_type: 'Full-time',
            employment_status: 'Active',
            date_of_joining: '2021-10-20',
            date_of_leaving: null,
            salary: 98000.00,
            bank_account_number: '2603715948',
            bank_name: 'Bank of America',
            emergency_contact_name: 'Walter Morgan',
            emergency_contact_phone: '(555) 123-4584',
            avatar_url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=400&fit=crop',
            created_at: new Date('2021-10-20').toISOString(),
            updated_at: new Date().toISOString(),
        },
        {
            employee_code: 'FIN-006',
            first_name: 'Larry',
            last_name: 'Bell',
            email: 'larry.bell@company.com',
            phone: '(555) 123-4585',
            date_of_birth: '1994-09-19',
            gender: 'Male',
            marital_status: 'Married',
            address: '654 Audit Avenue',
            city: 'San Francisco',
            state: 'CA',
            postal_code: '94144',
            country: 'United States',
            department: 'Finance',
            designation: 'Junior Accountant',
            role: 'Accountant',
            manager_id: 42,
            employment_type: 'Full-time',
            employment_status: 'Inactive',
            date_of_joining: '2022-06-15',
            date_of_leaving: null,
            salary: 85000.00,
            bank_account_number: '3714826059',
            bank_name: 'Wells Fargo',
            emergency_contact_name: 'Ruth Bell',
            emergency_contact_phone: '(555)