import { db } from "@/db";
import { employees } from "@/db/schema";

async function main() {
  const sampleEmployees = [
    {
      employeeCode: "ENG-001",
      firstName: "Sarah",
      lastName: "Chen",
      email: "sarah.chen@company.com",
      phone: "(555) 123-4501",
      dateOfBirth: "1985-03-15",
      gender: "Female",
      maritalStatus: "Married",
      address: "123 Tech Boulevard",
      city: "San Francisco",
      state: "CA",
      postalCode: "94102",
      country: "United States",
      department: "Engineering",
      designation: "VP Engineering",
      role: "VP Engineering",
      managerId: null,
      employmentType: "Full-time",
      employmentStatus: "Active",
      dateOfJoining: "2018-06-15",
      dateOfLeaving: null,
      salary: 185000.0,
      bankAccountNumber: "1234567890",
      bankName: "Chase",
      emergencyContactName: "Michael Chen",
      emergencyContactPhone: "(555) 123-4502",
      avatarUrl:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
      createdAt: new Date("2018-06-15").toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      employeeCode: "ENG-004",
      firstName: "David",
      lastName: "Martinez",
      email: "david.martinez@company.com",
      phone: "(555) 123-4513",
      dateOfBirth: "1991-06-30",
      gender: "Male",
      maritalStatus: "Married",
      address: "222 Software Street",
      city: "San Francisco",
      state: "CA",
      postalCode: "94108",
      country: "United States",
      department: "Engineering",
      designation: "Senior Software Engineer",
      role: "Software Engineer",
      managerId: 1,
      employmentType: "Full-time",
      employmentStatus: "Active",
      dateOfJoining: "2020-08-10",
      dateOfLeaving: null,
      salary: 135000.0,
      bankAccountNumber: "7890123456",
      bankName: "Wells Fargo",
      emergencyContactName: "Carmen Martinez",
      emergencyContactPhone: "(555) 123-4514",
      avatarUrl:
        "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop",
      createdAt: new Date("2020-08-10").toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      employeeCode: "ENG-005",
      firstName: "Jessica",
      lastName: "Lee",
      email: "jessica.lee@company.com",
      phone: "(555) 123-4515",
      dateOfBirth: "1992-12-05",
      gender: "Female",
      maritalStatus: "Single",
      address: "444 Code Avenue",
      city: "San Francisco",
      state: "CA",
      postalCode: "94109",
      country: "United States",
      department: "Engineering",
      designation: "Software Engineer",
      role: "Software Engineer",
      managerId: 1,
      employmentType: "Full-time",
      employmentStatus: "Active",
      dateOfJoining: "2021-02-15",
      dateOfLeaving: null,
      salary: 125000.0,
      bankAccountNumber: "8901234567",
      bankName: "Citibank",
      emergencyContactName: "Robert Lee",
      emergencyContactPhone: "(555) 123-4516",
      avatarUrl:
        "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop",
      createdAt: new Date("2021-02-15").toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      employeeCode: "SAL-002",
      firstName: "Robert",
      lastName: "Davis",
      email: "robert.davis@company.com",
      phone: "(555) 123-4533",
      dateOfBirth: "1987-09-14",
      gender: "Male",
      maritalStatus: "Married",
      address: "222 Sales Plaza",
      city: "San Francisco",
      state: "CA",
      postalCode: "94118",
      country: "United States",
      department: "Sales",
      designation: "Sales Director",
      role: "Sales Director",
      managerId: 1,
      employmentType: "Full-time",
      employmentStatus: "Active",
      dateOfJoining: "2019-08-01",
      dateOfLeaving: null,
      salary: 150000.0,
      bankAccountNumber: "7158924603",
      bankName: "Chase",
      emergencyContactName: "Jennifer Davis",
      emergencyContactPhone: "(555) 123-4534",
      avatarUrl:
        "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
      createdAt: new Date("2019-08-01").toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      employeeCode: "HR-001",
      firstName: "Patricia",
      lastName: "Campbell",
      email: "patricia.campbell@company.com",
      phone: "(555) 123-4565",
      dateOfBirth: "1986-05-30",
      gender: "Female",
      maritalStatus: "Married",
      address: "321 People Street",
      city: "San Francisco",
      state: "CA",
      postalCode: "94134",
      country: "United States",
      department: "HR",
      designation: "HR Director",
      role: "HR Director",
      managerId: null,
      employmentType: "Full-time",
      employmentStatus: "Active",
      dateOfJoining: "2018-03-10",
      dateOfLeaving: null,
      salary: 155000.0,
      bankAccountNumber: "3714826059",
      bankName: "Chase",
      emergencyContactName: "George Campbell",
      emergencyContactPhone: "(555) 123-4566",
      avatarUrl:
        "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=400&h=400&fit=crop",
      createdAt: new Date("2018-03-10").toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  await db.insert(employees).values(sampleEmployees);
}

main();
